src/Entity/SyncJob.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity]
#[ORM\HasLifecycleCallbacks]
class SyncJob {
    const STATUS_CREATED = 0;
    const STATUS_PENDING = 1;
    const STATUS_FAILED = 2;
    const STATUS_SUCCESS = 3;

    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private ?Uuid $id = null;

    #[ORM\Column]
    private ?int $status = null;

    #[ORM\Column(type: 'text', nullable: false)]
    private string $log = "";

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'jobs')]
    private ?User $owner = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?DateTimeImmutable $createdAt = null;

    public function __construct(#[ORM\ManyToOne(targetEntity: Placement::class, inversedBy: 'jobs')]
    private ?Placement $placement, #[ORM\Column(length: 255)]
    private string $filename) {
        $this->status = static::STATUS_CREATED;
    }

    public function markPending(): void {
        $this->status = static::STATUS_PENDING;
    }

    public function markSuccess(string $log): void {
        $this->status = static::STATUS_SUCCESS;
        $this->log = $log;
    }

    public function markFailed(string $log): void {
        $this->status = static::STATUS_FAILED;
        $this->log = $log;
    }

    /**
     * @return Uuid|null
     */
    public function getId(): ?Uuid {
        return $this->id;
    }

    /**
     * @return int|null
     */
    public function getStatus(): ?int {
        return $this->status;
    }

    /**
     * @return Placement|null
     */
    public function getPlacement(): ?Placement {
        return $this->placement;
    }

    /**
     * @return string
     */
    public function getLog(): string {
        return $this->log;
    }

    /**
     * @return string
     */
    public function getFilename(): string {
        return $this->filename;
    }

    public function getStatusAsString(): string {
        return match ($this->status) {
            static::STATUS_CREATED => 'Awaiting processing',
            static::STATUS_PENDING => 'Processing',
            static::STATUS_SUCCESS => 'Success',
            static::STATUS_FAILED => 'Failed',
        };
    }

    /**
     * @return User|null
     */
    public function getOwner(): ?User {
        return $this->owner;
    }

    /**
     * @param User|null $owner
     */
    public function setOwner(?User $owner): void {
        $this->owner = $owner;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void {
        $this->createdAt = new DateTimeImmutable();
    }

    /**
     * @return DateTimeImmutable|null
     */
    public function getCreatedAt(): ?DateTimeImmutable {
        return $this->createdAt;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity]
class User implements UserInterface, PasswordAuthenticatedUserInterface {
    #[ORM\Id]
    #[ORM\Column(type: "uuid", unique: true)]
    #[ORM\GeneratedValue(strategy: "CUSTOM")]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private ?Uuid $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(options: ["default" => 0])]
    private int $maxInvites = 0;

    #[ORM\OneToMany(mappedBy: "owner", targetEntity: SyncJob::class)]
    private ?Collection $jobs = null;

    #[ORM\OneToMany(mappedBy: "owner", targetEntity: Placement::class)]
    private ?Collection $placements = null;

    #[ORM\OneToMany(mappedBy: "owner", targetEntity: WebDavCalendar::class)]
    private ?Collection $calendars = null;

    #[ORM\OneToMany(mappedBy: "owner", targetEntity: Invite::class)]
    private ?Collection $invites = null;

    public function __construct() {
        $this->jobs = new ArrayCollection();
        $this->placements = new ArrayCollection();
        $this->calendars = new ArrayCollection();
        $this->invites = new ArrayCollection();
    }

    public function getId(): ?Uuid {
        return $this->id;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(string $email): self {
        $this->email = $email;

        return $this;
    }

    public function getUserIdentifier(): string {
        return (string) $this->email;
    }

    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password): self {
        $this->password = $password;

        return $this;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(string $name): self {
        $this->name = $name;

        return $this;
    }

    /**
     * @return SyncJob[]
     */
    public function getJobs(): array {
        return $this->jobs->toArray();
    }

    /**
     * @return Placement[]
     */
    public function getPlacements(): array {
        return $this->placements->toArray();
    }

    /**
     * @return WebDavCalendar[]
     */
    public function getCalendars(): array {
        return $this->calendars->toArray();
    }

    public function isAdmin(): bool {
        return in_array("ROLE_ADMIN", $this->getRoles());
    }

    public function getRoles(): array {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = "ROLE_USER";

        return array_unique($roles);
    }

    public function setRoles(array $roles): self {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Invite[]
     */
    public function getInvites(): array {
        return $this->invites->toArray();
    }

    public function getMaxInvites(): int {
        return $this->maxInvites;
    }

    public function setMaxInvites(int $maxInvites): void {
        $this->maxInvites = $maxInvites;
    }
}

templates/_modal.html.twig
<div
        class="modal fade"
        tabindex="-1"
        aria-hidden="true"
        data-modal-target="modal"
>
    <div class="modal-dialog" style="display: table; min-width: 500px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" data-modal-target="modaltitle">Log</h5>
                <button type="button" class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body" data-modal-target="modalbody">
                Loading...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

templates/_navbar.html.twig
{% macro menuItem(name, route) %}
    <li class="nav-item">
        {% set isActive = app.request.attributes.get('_route') == route %}
        <a class="nav-link{% if isActive %} active" aria-current="page{% endif %}" href="{{ path(route) }}">{{ name }}</a>
    </li>
{% endmacro %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path("landing") }}">Rota Processor<sup class="text-danger">BETA</sup></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if app.user %}
                    {{ _self.menuItem("Home", 'landing') }}
                    {{ _self.menuItem("Placements", 'list_placements') }}
                    {{ _self.menuItem("WebDAV Calendars", 'list_calendars') }}
                    {{ _self.menuItem("Jobs", 'list_jobs') }}
                    {% if app.user.admin %}
                        {{ _self.menuItem("Users", "list_users") }}
                        {{ _self.menuItem("Invites", "list_invites") }}
                    {% endif %}
                {% endif %}
            </ul>
            {% if app.user %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-fill"></i>
                            {{ app.user.name }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ path('profile') }}"><i class="bi bi-pencil-fill"></i> Profile</a></li>
                            <li><a class="dropdown-item" href="{{ path('my_invites') }}"><i class="bi bi-person-fill-add"></i> My Invites</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_logout') }}"><i class="bi bi-box-arrow-left"></i> Log out</a></li>
                            {% if is_granted('IS_IMPERSONATOR') %}
                                <li><hr class="dropdown-divider" /></li>
                                <li>
                                    <a class="dropdown-item" href="{{ impersonation_exit_path(path('list_users')) }}">
                                        Exit impersonation
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            {% else %}
                <a class="nav-link" href="{{ path('app_login') }}"><i class="bi bi-box-arrow-in-right"></i> Login</a>
            {% endif %}
        </div>
    </div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width" />
        <title>{% block title %}Welcome!{% endblock %} | Rota Processor</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% include '_navbar.html.twig' %}
            <div class="body-container">
                {% for type, messages in app.session.flashbag.all() %}
                    {% for message in messages %}
                        <div class="alert alert-{{ type }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% block body %}{% endblock %}
            </div>
        </div>
    </body>
</html>

templates/calendars.html.twig
{% extends 'base.html.twig' %}

{% block title %}WebDAV Calendars{% endblock %}

{% block body %}
<h3 class="page-title">WebDAV Calendars</h3>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Colour</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for calendar in calendars %}
        <tr>
            <td>{{ calendar.name }}</td>
            <td>{{ calendar.username }}</td>
            <td>{{ calendar.color }}</td>
            <td>
                <a href="{{ path('edit_calendar', {id: calendar.id}) }}">Edit</a>
                | <a href="{{ path('delete_calendar', {id: calendar.id}) }}">Delete</a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="20">
                <a href="{{ path('new_calendar') }}" class="btn btn-secondary" style="width: 100%;">+ New Calendar</a>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ical.ics.twig
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//rota.youd.family//RotaProcessor//EN
X-WR-CALNAME:{{ placement.name }}
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
{% for shift in shifts %}
BEGIN:VEVENT
UID:{{ placement.id }}-{{ loop.index }}
DTSTART:{{ shift.start | date('Ymd') }}T{{ shift.start | date('His') }}
DTEND:{{ shift.end | date('Ymd') }}T{{ shift.end | date('His') }}
CATEGORIES:{{ placement.calendarCategory }}
ICAL-DATA:{}
SUMMARY:{{ placement.prefix }}{{ shift.title }}
END:VEVENT
{% endfor %}
END:VCALENDAR

templates/invite_expired.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invite already used{% endblock %}
{% block body %}
    <h3 class="page-title">Invite already used</h3>
    <p>
        This invite has already been used, please ask to be re-invited. If you have already filled
        in the sign-up form, try logging in with the details you submitted.
    </p>
{% endblock %}

templates/invite_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New invite{% endblock %}

{% block body %}
<h3 class="page-title">New invite</h3>
{{ form(form) }}
{% endblock %}

templates/invite_non_left.html.twig
{% extends 'base.html.twig' %}

{% block title %}New invite{% endblock %}
{% block body %}
    <h3 class="page-title">No invites remaining</h3>
    <p>You have no invites remaining. Please contact the person that invited you or an
        administrator.</p>
{% endblock %}

templates/invites.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Invites{% endblock %}

{% block body %}
    <h3 class="page-title">All Invites</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Date created</th>
            <th>Owner</th>
            <th>Comment</th>
            <th>Email used</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for invite in pagination %}
            <tr class="invite-{{ invite.used ? 'expired' : 'valid' }}">
                <td>{{ invite.createdAt | ago }}</td>
                <td>{{ invite.owner.name }}</td>
                <td class="small">{{ invite.comment }}</td>
                <td>{{ invite.emailUsed }}</td>
                <td>
                    {% if not invite.used %}
                        <a href="{{ path('signup_with_invite', {id: invite.id}) }}">Get link</a>
                        | <a href="{{ path('revoke_invite', {id: invite.id}) }}">Revoke</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        {% if app.user.maxInvites != 0 %}
            <tr>
                <td colspan="20">
                    <a href="{{ path('new_invite') }}" class="btn btn-secondary" style="width: 100%;">+ New Invite Link</a>
                </td>
            </tr>
        {% endif %}
        </tbody>
    </table>
    {{ knp_pagination_render(pagination) }}
{% endblock %}

templates/invites_mine.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Invites{% endblock %}

{% block body %}
    <h3 class="page-title">My Invites</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Date created</th>
            <th>Comment</th>
            <th>Email used</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for invite in invites %}
            <tr class="invite-{{ invite.used ? 'expired' : 'valid' }}">
                <td>{{ invite.createdAt | ago }}</td>
                <td class="small">{{ invite.comment }}</td>
                <td>{{ invite.emailUsed }}</td>
                <td>
                    {% if not invite.used %}
                        <a href="{{ path('signup_with_invite', {id: invite.id}) }}">Get link</a>
                        | <a href="{{ path('revoke_invite', {id: invite.id}) }}">Revoke</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        {% if app.user.maxInvites != 0 %}
            <tr>
                <td colspan="20">
                    <a href="{{ path('new_invite') }}" class="btn btn-secondary" style="width: 100%;">+ New Invite Link</a>
                </td>
            </tr>
        {% endif %}
        </tbody>
    </table>
{% endblock %}

templates/jobs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jobs{% endblock %}

{% block body %}
<h3 class="page-title">Rota processing jobs{% if placement is defined and placement is not null %} for {{ placement.name }}{% endif %}</h3>
<div {{ stimulus_controller('modal') }}>
    {{ include('_modal.html.twig') }}
    <table class="table" >
        <thead>
            <tr>
                <th>Created</th>
                <th>Placement</th>
                <th>Processor</th>
                <th>Status</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            {% for job in pagination %}
            <tr>
                <td>{{ job.createdAt | ago }}</td>
                <td>{{ job.placement.name }}</td>
                <td>{{ parsers[job.placement.processor] }}</td>
                <td>{{ job.statusAsString }}</td>
                <td>
                    <button
                            class="btn btn-secondary btn-sm"
                            data-action="modal#openModal"
                            data-url="{{ path('get_job_log_json', {'id': job.id}) }}"
                            data-title="Log for job {{ job.id }}"
                    >View log</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
    {{ knp_pagination_render(pagination) }}
{% endblock %}

templates/landing.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome!{% endblock %}

{% block body %}
    <h3 class="page-title">Welcome!</h3>
    <p>This is a rota processor tool, designed to trawl your rota spreadsheets and add the shifts
        to a remote calendar</p>
    <h4>Usage</h4>
    <ol>
        <li>
            Create a placement, choosing a suitable processor for your spreadsheet, and choose
            "Built-in WebCal Calendar"
            <ul>
                <li>The prefix will be added to the beginning of the name for each shift, leave
                    blank if not needed</li>
            </ul>
        </li>
        <li>Upload the spreadsheet to the placement and wait for its processing to complete on the
            jobs page</li>
        <li>Copy the iCal link from the placements page and import this on to your device or into
            Google Calendar or Outlook
            <ul>
                <li><small><i>Google Calendar</i> (web): Settings cog > Settings > Add Calendar > From URL</small></li>
                <li><small><i>Outlook</i> (web): Add calendar > Subscribe from web</small></li>
            </ul>
        </li>
    </ol>
    <h4>Getting help</h4>
    <p>Please speak to the person that gave you access to this system for any issues with processing
        rotas, or requesting new rota format support</p>
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% set showNav = false %}

{% block title %}Login{% endblock %}

{% block body %}
<h3 class="page-title">Login</h3>
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" name="_remember_me"> Remember me
        </label>
    </div>

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/signup_with_invite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Signup{% endblock %}

{% block body %}
    <h3 class="page-title">Signup</h3>
    <p>
        You've been invited by {{ invite.owner.name }} to create an account. Please fill in the details below.
        <br />
        <small>Your email address will be visible to server admins and the user that invited you ({{ invite.owner.name }})</small>
    </p>
    {{ form(form) }}
{% endblock %}